  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        cd backend
        cd smartMoney_project
        python manage.py migrate
    - name: Run tests
      run: |
        cd backend
        cd smartMoney_project
        pytest
    - name: Run coverage
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd backend
        cd smartMoney_project
        coverage run --source='smartMoney_app' manage.py test
        coveralls --service=github
