name: build-n-test
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install statisticframe
      run: |
        pip install .
    - name: Run tests
      run: |
        cd ./src/tests && python -m unittest discover -s . -p 'test_*.py' -v -b
